<?php
// Generated by ZF2's ./bin/classmap_generator.php @ Sun, 15 Jan 2012 19:44:21 -0700
return array(
    'WdevZfcuserApigility\Module'                            => __DIR__ . '/Module.php',
    'WdevZfcuserApigility\Document\User'                     => __DIR__ . '/src/WdevZfcuserApigility/Document/User.php',
    'WdevZfcuserApigility\Document\UserMappedSuperClass'     => __DIR__ . '/src/WdevZfcuserApigility/Document/UserMappedSuperClass.php',
    'WdevZfcuserApigility\Event\ResolveTargetEntityListener' => __DIR__ . '/src/WdevZfcuserApigility/Event/ResolveTargetEntityListener.php',
    'WdevZfcuserApigility\Mapper\UserMongoDb'                => __DIR__ . '/src/WdevZfcuserApigility/Mapper/UserMongoDb.php',
    'WdevZfcuserApigility\Options\ModuleOptions'             => __DIR__ . '/src/WdevZfcuserApigility/Options/ModuleOptions.php'
);